# Site settings
name: No Name

# Jekyll Config
exclude: ['Gemfile', 'Gemfile.lock', '*.scss', 'node_modules', 'gulpfile.js', 'package.json', '.gitignore', 'js/*.js']
markdown: kramdown

# Asset Building Config
assets:
  css_compressor: sass

sass:
  sass_dir: _sass
